
# Homepage HTML in string format
acronym_string = '''<strong>Met</strong>abolomic<strong>s</strong> <strong>T</strong>reatment and
<strong>A</strong>nalysis Software'''

homepage_string = '''This software is geared towards FT-ICR-MS extreme-resolution <strong>mass spectrometry data</strong>.
<br>
<br>
It is still in the <strong>early stages of development</strong>. As such, much progress in the different areas
of the software from presentation to available tools and features is expected to happen regularly.
<br>
<br>
- It is suited to read the output generated by the MetaboScape 5.0 software (Bruker Daltonics). It can however read any
other type of data if it follows the formatting rules as declared in the "Data Reading" page.
<br>
- Thus, it can handle not only Direct Infusion FT-ICR-MS data but also LC-MS and GC-MS data. It will not use the time
retention parameters of the latter 2 and as such may not be the most suitable tool to analyse said data.
<br>
<br>
- This software includes reading the data, data filtering, data annotation based on mass (or <em>m/z</em> peak)
deviation, data pre-treatment, univariate, multivariate unsupervised and supervised analysis, common and exclusive
compound analysis and data diversity visualization tools (Van Krevelen and Chemical Composition Series).
<br>
- It also includes statistical analysis performe on data treated with Binary Simplification (BinSim),
that is, feature occurrence data that can be useful for extreme-resolution data with plenty of missing values.
<br>
- Data Annotation is made based on the metabolite database given by the user. This database should be formatted according
to the indications in the "Data Annotation" page.<br>
- Every Figure generated by the software can be downloaded and a final report of the analysis can also be generated.
<strong>(TODO)</strong>
<br>
<br>
<hr />
<br>
- Software made by: <strong>FT-ICR and Structural Mass Spectrometry Laboratory, BioISI, Faculdade de Ciências da
Universidade de Lisboa</strong> (<a href="http://ft-icr.rd.ciencias.ulisboa.pt/" target="_blank"
rel="nofollow">ft-icr.rd.ciencias.ulisboa.pt/</a>)
<br>
<br>
If you use this software in your untargeted metabolomcis data analysis, we would be grateful if you cite our paper
introducing it:
<br>
<br>
- Paper Link: <strong>(LINK)</strong><br>
- Citation: <strong>(CITATION)</strong>
'''


# Instruction page HTML in string format

instructions_page = '''<p>Here, we will go through some general considerations to have while using this software by describing
how it works and some of the currently known issues overall that exist. Furthermore, if you encounter an issue or problem
with the software feel free to inform us at
<a data-fr-linked="true" href="https://github.com/fticr-sms/Metabolomics_DataAnalysis_Pipeline/issues/new">https://github.com/fticr-sms/Metabolomics_DataAnalysis_Pipeline/issues/new</a>.
Furthermore, if you feel some parts are underexplained or cannot be intuitively grasped, please also inform us so we can
improve the descriptions provided.</p>
<p><strong>General Considerations to Have</strong></p>
<p>- If you have reached this page, we are assuming that you have all the needed required Python packages and their versions
that were outlined in the README.md to run this software.</p>
<p>- This software is both presented in Jupyter Notebook format as well as this graphical interface. Each of them has unique
parts and sections that are only present in one of these formats. In general the former can have results and outputs be
more easily editable and customized to the user (requiring basic programming background) while the latter is more suited
for a quick analysis for users less experienced with Python programming at the cost of not being able to expand the
analysis further than what is already present in the software.</p>
<p>- While on data pre-processing and pre-treatment, steps will be unlocked one by one starting with <strong>Data
Reading</strong> which is the only one unlocked at the begginning. When reaching the final step of this section in
<strong>Class Colours</strong>, after selecting <u>Next Step - Analysis</u>, <strong>all analysis steps</strong> become
unlocked (as well as <strong>Report Generation</strong> - still <strong>TODO</strong>). These steps are generally
independent of one another and can be done in any order or skipped based on the type of analysis to be performed. As with
every Metabolomics experiment, statistical analysis results will depend on the filtering and pre-treatment methods used.</p>
<p>- If you <strong>change any part of the pre-treatment steps</strong>, posterior pre-treatment steps and statistical
analysis will immediately <strong>be locked</strong> and will <strong>erase previous statistical analysis</strong>, so you
will have to repeat data pre-treatments. This is to avoid situations where the user wanted to change the pre-treatment but
forgot to re-apply posterior pre-treatment steps.</p>
<p>- While there is an effort for figures and tables produced that can be downloaded to have the relevant parameters used
to build them in the name, it is a good practice to keep in mind what parameters were used to make these figures and tables,
especially those that do not update with every parameter change to safeguard possible errors that may arise in the filenames
generated.</p>
<p>- All tables saved will be downloaded to your current working directory, that is the folder where you are running the
interface from. As for figures, there are figures that were created using the Python package "Plotly" (interactive figures)
and others created using the Python package "Matplotlib" (statis figures). The former are saved in your downloads and are
downloaded using the toolbar that appears at the top right of the figure when hovering over it. The latter are saved using
an available button in the software and are downloaded to the current working directory identically to the tables.</p>
<p>- When you start running something there is not a way to stop the process. You can observe if the program is running by
observing the little circle on the top right. If there is something currently running it will have this aspect:
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAtCAYAAADsvzj/AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFxEAABcRAcom8z8AAAl7SURBVGhD3Vh5WNTXFUVFjdFEm5oYTe2X5jPWvSqCyqLgVhuS1lh3bZtqTGzQKIiKxqVapFqNSzQ22hqTVE1iSqKILMpiBFEQlwgIuLCJ7MvMIGpM0tNz3zDpdPpwGPAf+sf5ZrjM771737n33Pt+Tk4Bx/B/Aa2xOUJrbI7QGpsjtMbmCK2xsfAPh9Mi4s2j/DsKTktj4bQkxgYn4BQYDafF/P/iyP9do7HQGh2BPyHOyyf/brs0Et3WxqJr4KfoMHsX2s/dg8de3Y0Oc/9G7MGj8/bBecFnaLXwc7TwZ8CWoGzXdRRaY0MhzqtAjuGJlccxdFsCXt6bDL8DSfiVfwh6jnwZPx03A73HTkOvn88iZqCH7xx0nbISnWdtQMc5O9HWb79VQE1gSGtsCOqC6LQiGs+vj8OMD8/hYEoezlwrQnj8acz1W4T+g4dj8LARGOI+kvCGi7sP4Y1BXuPRZ8wUFdyzE+aj0+ztaLnoCAOJ4NoCm70aAq3RHhQL4WgfFMUAUrH39DUkZt9CWaUBtbdNKCq8iXXrgtF/oCuGuLnDbZgnXId5Kch3gQrMYxQGe41F37FT8KNJy9B+3vtkh2naGGa0xgdhYTha8uSe/VMsJr2fgojLBag2GFBjMuBOjQnf3L0N4D4+/SwU7r5T0MdnAvqMnqScdvEcjUEjxsNtqAeD8VJMWYL7mbcvuk8MUHXUyj+sjh3N/vVBa3wAWpCN50PisfRwGqLTClBeWY37tTX45k4NviVyiysRkXYLr++NQ4952/HErI34wW83o/uvl+CZycvRdepK9Bk7Fa7DR2LoUHd+/if1Bni/yN8F4pE39ptrxpE00xrrw4IwdKciLTuShrPXi8lENW6bjDAZDSgur1TpFRx5BQM2nuTvmR7+dEROlqnScuFhlZItFoWh0++34bmXXleOSxBuwzwUM/K975jJ6DJ9Ldr4fWxOM50fOmiNOnBR54VHMeujVFzMLVFM1DCIu6yJgtIKvPtlNjzfScAza2LgLM5TydSJSr7boAXXa00JfnJmCHqPm8a086ljZYRiqP+oCXh62hol02ZWBDb+2EJrtEVdn3B7+xQ+SclRLNSQhRqjEd/erUHo+Ty4bT2lHJQaUo3Rdg1rZ6RvMHVEqaQmuk9cjP4+v/yeHRcPbzI2D+3Yc9RacgD/tZYGWqM16hTq8RVRCPziMrILy1HLoq5lMBJQ5s0yvHLgPJzld2RMH0Q9kDog2vodRLfJQRjsOeb7uulHVrpOW61SzJyedljRGq1BB1vys/eGeOyIz8bN0krWhKSUUdWI1ES31cdZPw4GYYEaVaLUBCCNU4JwHe6p0q3nC68oxpwChJWmBkI2nAMjMGJHIg4m32CvqMK9WpNi42RmIYYypZz82MyEEd3zdiEORqD1/EOqLvqN8IWLiysGug5HD6+X0H7aes5un5M5O2OM1mgNpssjnJ+mfnAOKVQqkdh7LPCMgjLMOXgeHZdzAzUkap5tMCR1Iplin6CX72x4uHvC3csHnuMnYuDcYDweEGpmTvtsHbRGa8wPU3PUxuOZyC+pYCAmpVgfJt1A93WcZlVKaZ5zFHRUxGL4wm14bUEglgatwM73/o690SlwociIH9rnLNAarcEFfrgyGttis1R9iNxKB4/JKESfDewXio1G1IYtKNetl0Ri9r4ERCemIisjDTm5eYhML8SQrYlweoPpq3vOAq3RGgykMwN5Jz4Lt8oq2cVNqKquxj9T89CLHb5+uXUQdaPPa4cuI7PIAHx3H7W1tQi7lI8Bf+GB+T0ERp5cdRy72PCKy6vwL/aNG0XlWHMsXU2+KrV0zzkKBvLosii8FZaOHI45X3Psqa424OjFPAzcxEAeCiMMRKRXGJEGWMgU28pU62KRXd1zjkAYZSBPrTqhak/S9y7Tt4K1eOhcDvptJPNNZoQLPLX6BPadvo5SkV5uUlFVjQ+4YRfa7W7QULDWWi+JwOrwdFWLah8GEno+9yGlFk+8I1NoFTfIvlWmTksm3aSrRegrw6GoSVNrhL1Kmu6gzV+SgVw1hMoekgFrIzLQ7Y88MHvMa43WIOVyUuP+egbR6QWqEX4n6cVNAkK/UkNikwPhYXTkCPR2TCZKKqpUr5Jgzly9hZm8eT4mvUpERfesBVqjNWRg5GfPkDjsPnUV5Uwrod1oMOIsWXlxz1nzb+xtVB+YUm0p375cJz2/RDFx22TiBFGNwxfyMG5XknqhYfGjXmiN1pBmR4hy+R26iHM3ihUrEoyJwYREX+EdhaxIII4MjWpd/pZsDNzElKKcV/KQJHVra4xKIfclXUcvzngqCHvrao224KYtF/NmuD4OW2Ky1CbSFGt5cmn5pZTiDPRlc2yl7iEMxt7pCeS+wuA7c2pYHpampgUJQlLqa35eyClWI1CHILLRkBFIa9SBG7cjxXM4sssmcmrCjIH3dVGZIxfzMZOXLrXx/LpgLKcun7KG+ttsk/mtC1mWK8AZpugdricHY2DvkLTacTJbZUGDWdYa64HMQs8Fx8GfRS6qJUHIOC/FL5+pTLtNJzIxeudpNTGrgMRxXpGV6oiE/uGIevsiLy52nrzKQylBJScF88sLI2+blTiQnINR7yaZmZBAbPzQQmusD+LUm+H48bpYJccZTCsTWTEyoNt0RMYXuauIuv1ufyp8d5/Fqx9fgOf2RLhtOaWuAiIObx1NQ9yVQnVVZrGpehN2s3hJ++jsDbzA59qzy5uZbAAbAq3xQWDKtFsWCfftCZTLLDXOS5rJaYpj8l0cu0L7pbwSFLGe5JXRF1SgeN5f5IapOjdhSU+pN7HLJc2bbKrRx5KaOh900BrtgZu0DoxU4/Uman96fplSHHm/ZWSxmvPdHJh8lxQUyP8siidBCHu5xRVIyCpU6/Rmg1WCIXs4EoRAa7QH2YTByNuSrlSdycz3/UyJZF68LuUWo5RN7R5rRpwWyOmL82bWDKjiFTmvuBzJ14p4z7mCX7x3Br3/HI9WUlci444GIdAaGwqhn1NpGzowmOPFdHbhgNBL2HwiC1FpBSooEYB01tJFFrW8qPgqrxQHUnIQdCRNvS+WMUcJgzjfEHWqD1qjoxBloQi04SjzNAfJnwTHUnVOK0cn70vGb/5xDtN5VRapFYl23ZKgpFV1bHne0XrQQWtsLORExSmBSKctRILlU9JHOS/QrNMYaI1NgUoRQZ2zOjzMACzQGpsjtMbmCK2xOUJrbI7QGpsdjuHf3S99jHLLRqMAAAAASUVORK5CYII="
style="max-width: inherit; cursor: pointer; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size:
medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing:
normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px;
-webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness:
initial; text-decoration-style: initial; text-decoration-color: initial; width: 25px; height: 22.1154px;" width="50"
height="45">. Otherwise, it will have this
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAeCAYAAABNChwpAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABdaVRYdFNuaXBNZXRhZGF0YQAAAAAAeyJjbGlwUG9pbnRzIjpbeyJ4IjowLCJ5IjowfSx7IngiOjMyLCJ5IjowfSx7IngiOjMyLCJ5IjozMH0seyJ4IjowLCJ5IjozMH1dfdp0gPkAAAQ1SURBVFhHxZdbbJNlGMf/PR/Wdls7mOtwEGQDHAREVEaMCSYmHiAhhDvFW+IFmnjlBSbeCndwzQ1cwI3BSBZJuDABBTXqPACTo8DObh1du3Zt13Y8/3fft77d15V1HPZLmvX7+h3+7/M+z/N/ZsPn3TNYRuzG32Vj2QUsegvsNhuiITc2v1CHRq8T7REvtq8KobO5Dh6HHTdjU/jxXhw/3Injz6FJjE/ljTur81gB8l6EfS68s64RO1eH8F5HGCvqXMavJQrylERmGoOJHG6PZ3DlQQJnr41hZDJnXFGZqgIcdhteXunHwdda5OX1WBv2Gr9Up1CcwYAIOXt9DN/1xtAzmIScqogDXR9+ZXwvQ96NrrYQvnx7Dd7taESTtupYehp3ZZVctdthg5MXa3C76mWbOkV8c8CtojCYzGGmgogFI/BqaxCf7WzF++vDcy+4MZrG9f/T+GNwEsevDKhzJOhxIOJ3qc/ejREckvtM8rL0n+4ncPjCf7g6krKIqBgBqv7olWbs64zA53Koc7/0JXHkUj+OXurDr/1Jdc4kJ6GIZ/IYklUyMn9JEtokCh1Nvrnk9Tnt6hlT00XjrlkqCjggL/9YPitFCOm+MY6vL/apDH8cEyLk6khahbw94seqeo/KpYDHiWE5xwjqQbD0gbDPqfa+VVSbnOsdw8+S1bXA64/JNnHbCBOYVcRo6FgEbG0JYJ1cTNXk+OUBKanykC+W7n9jasUmLGH2ER2LgF0vNZSp/FbK6H48YxzVDhOWVUPYP9jEdCwC3lzTgJC3vOSeBFYLk9OEHVTHIqAj4oOU9hxPKoCwPE3YvnUsArKFUplk80UkswXjaOkwsU3oHToWAdekWZgs1lCqwSblkR5gQuPSsQj4rb9Ubk87/GzddE0di4BbsVLGtwTdONRVaqtLQRdAt6Rl61gEPJRONpqaXTlv3hYNqO9LYXWDV3mDCa16fje1CPhnOIXvb44bR1B2/MGG0kNqoastOGdMtGjOCRxWdCwCqPKyuBdNhaxf4censg07pD3XAq/fs7HJOIKaDzikzE9sixnRKNg42I43yOrZkmkojTIV0fuT2aIynGowYl+81YZdaxvUcTKbx+m/R3GqZwSpXHlZV3TDjNR/30RW7HTWzWiptNbd8uC8pHJCegNLqyDmTis2YcJ+8kYU+zc1YYt4CuE8cOF2HCfl5bfmVQBZcCDhyne8GMTB16Oyknqp5/IebsJmxbCyZFk1etbnpKnRyI5cfKDCX2ksW3Ak4+QykMiKEWWRliEiGvQg4HaoaOhwWmKz4ezgN4YXwhw6L8nMAaZnKFX7TEh4D/OhVyx1UvZuSlbLbHZJLridFDN7nQ5L+BuZhs/Inp/4fVg56UIvJ4v+v4Cwp3NeoGXTNWlc9A62b3ZQNjH2EZYyq6lYaQqdR00CngWWPvB8AR4Buu7Olh/yrToAAAAASUVORK5CYII="
style="width: 22px; height: 20.9px;">&nbsp;aspect.</p>
<p>- Resetting the program will reset all your variables and previously performed analysis.</p>
<p><br></p>
<p><strong>Possible Problems and Suggested Fixes</strong></p>
<p>- The main overarching problem when running the program is the de-formatting of the pages that can happen when you go
back and forth between different pages causing artifacts of different pages or empty spaces before the pages to show up.
We currently believe this is an issue with the panel package we are basing this software on. Fortunately, this can be
mostly solved when using the program by refreshing the page in the browser to reset the layout of the page. However,
<strong>do not use&nbsp;</strong>this trick on the <strong>common and exclusive compound page</strong> since this has a
small chance to make the sidebar to navigate the software disappear, rendering it unoperable and needing to be closed and
opened again.</p>
<p>- Another issue of the same type is the <strong>reset floatpanel</strong> not appearing when pressing it the 2nd time. It
is once again a problem fixed by refreshing.</p>
<p>- Do not mash the buttons many times, it will buffer the clicks. See first on the upper right if the program is running or not.</p>
<p>- Other known issues have smaller consequences and affect specific pages. When they exist, a little note in bold will
indicate the problem at the beginning of the corresponding page. In general, there is in average 1 possible issue in each
page of the analysis section.</p>
<p><br></p>
<p><strong>Performance of the Different Parts of the Program</strong></p>
<p>- The program generally runs smoothly and quickly with low latency and chugging. The exceptions are the very first page
when data reading which can slow down the program for a few seconds as well as some parts when certain analysis such as
PLS-DA or Random Forest finish and the page layout is updated with the results.</p>
<p>- The possible slow downs and time of analysis is also dependent on the size of the dataset. The bigger the dataset to
be analyzed, the slower the analysis is and vice-versa.</p>
<p><br></p>
<p>We hope you find this software useful.</p>
<p><br></p>
<p>With our best regards,</p>
<p>The FT-ICR-SMS Laboratory MetsTA Development Team</p>'''


# Data Reading Description HTML in string format

data_reading_opening_string ='''<strong>Input your Excel or csv MetaboScape file.</strong>
<br>
This process can take a while for larger datasets.
<br>
If your file is not from MetaboScape, it should have the feature peak column be called 'Bucket Label'. This column should
represent the metabolic features "neutral mass" if possible. Albeit not necessary, it will allow to perform annotation
later on in the software.
<br>
<br>
In general, your file should have your detected features in the rows and sample data and meta data in the columns. The
detected features should be in the first column which must be named 'Bucket Label'. You will be asked later to identify the
meta data columns to separate them from the remaining ones.
<br>
<br>
If the 'Bucket Label' comes from MetaboScape or can be interpreted as a float (number), an extra columns called 'Neutral Mass'
will be automatically added to your data.
<br>
Otherwise, a notification will inform that this column could not be added. If a Neutral Mass column does not exist and could
not be created in this way, you will not be able to perform annotation using this software.
<br>
Currently, after confirming your dataset and moving to the next page, you will not be able to change it unless you restart
the program or reset every variable.
'''


# Data Multiple Annotation De-Duplication Description HTML in string format

annotation_deduplication_opening_string = '''<p>Due to the proximity of mass values, the same compound (or formula) can be
annotated to the different metabolic features.</p>
<p>Since one (adduct of one) compound should result in only one (monoisotopic) mass, this section <strong>can merge
metabolic features that share compound annotations into one single metabolic feature</strong>. For example, there is no
biological reason for multiple peaks being associated with a compound. Most of the time, there is one <em>&apos;main&apos;
peak</em> with much higher intensities across the samples, although this is not always observed.</p>
<p>This section is the least streamlined and automatized part of the data analysis pipeline we present. This is due to the
multiple situations that can arise with different possible solutions, specifically a situation that warrants individual
attention that can arise when multiple annotations are performed on the data. When finding different metabolic features
with the same annotation in a database used, featuress are <strong>merged by keeping the highest intensity value in each
sample </strong>of the features with the same annotations. Thus, there is a total of 4 possible situations:</p>
<p>- <strong>Situation 1 (Overwrite)</strong>: Multiple metabolic features have the same annotation for one annotation
database (and no other database has different annotations for those features) with the highest intensity values coming all
from one metabolic feature that becomes the <em>de facto</em> metabolic feature with others being erased.</p>
<p>- <strong>Situation 2&nbsp;(Merge Same Adducts)</strong>: Multiple metabolic features have the same annotation for one
annotation database (and no other database has different annotations for those features) with the highest intensity coming
from at least two different metabolic features and <strong>ALL</strong> features come from the same adduct (<u>including
ones that are not used for the merge</u>). &apos;Bucket Label&apos; and &apos;Neutral Mass&apos; columns become the weighted
average (based on the average intensity of the features) of all the features with the same annotation. Since this software
does not yet allow for adduct information, this is the approach used always between situation 2 and 3.</p>
<p>&nbsp;- <strong>Situation 3&nbsp;(Merge Different Adducts)</strong>: Identical to Situation 2 but there is at least one
metabolic feature that comes from a different adduct. Since this sofware does not yet allow for adduct information, this is
the approach used always between situation 2 and 3.</p>
<p>- <strong>Situation 4&nbsp;(Contradictions - Possible Problem Situation)</strong>: Multiple metabolic features have the
same annotation for one annotation database and different for another annotation database. Most of the time there is no issue.
For example, imagine a case where we have annotated with two databases: HMDB and LOTUS. <strong>Scenario 1:</strong> We find
that HMDB puts two different compounds for 2 metabolic features and LOTUS puts the same compound. Here, it is fair to treat
them as different features and this is the default behaviour. However, if one annotation is less reliable, for example a
formula annotation, you may prefer to merge the peaks despite this. <strong>Scenario 2:</strong> However, rarely, there can
be a case where there are <strong>more than 2 metabolic features</strong> with the same compound annotated in HMDB. This
should <strong>be quite rare and it is from where the problem arises</strong>. A scenario can arise where HMDB puts the same
compound for 4 features and LOTUS assigns to one of them one compound, to a second one a different compound and the last two
ones does not assign a compound at all. What is the correct course of action? &nbsp;Perhaps merging the two peaks with no
annotation by LOTUS, maybe merging those two peaks with one of those annotated by LOTUS since they would be normally merged
if not for the existence of two different LOTUS annotations. Hence, the problem. We concluded that they should be seen on a
<strong>case-by-case basis&nbsp;</strong>with the user deciding which (if any) peaks they prefer to merge.</p>
<p><br></p>
<p><h3>Initial report of the observable multiple annotations for each annotation (including formula
annotation) performed</h3></p>'''


# PLS-DA Description HTML in string format

plsda_opening_string = """Here, <strong>Partial Least Squares - Discriminant Analysis</strong> models can be built.
<br>
<br>
As the number of components (Latent Variables) to use in a model such as this one is of essential importance, first we will
start with an optimization of this number. This is performed by fitting a PLS model in your data from a chosen initial
number of starting components to a chosen final number of components. The <strong>Q<sup>2</sup> and R<sup>2</sup></strong>
scores are then estimated by stratified cross-validation (number of folds <strong>K</strong> is also chosen by the user).
The chosen number of components should be the number <strong>where Q<sup>2</sup> specifically</strong> stops increasing. A
figure is provided to evaluate this.
<br>
<br>
- <strong>Q<sup>2</sup></strong> - Mean squared error of PLS-DA predictions based on the test samples, thus it is ideal
to test if the model will overfit. This will increase until a certain number of components that should be chosen. Then
it usually stabilizes but from a certain point it might start to decrease which would mean the model is overfitting.
<br>
- <strong>R<sup>2</sup></strong> - Mean squared error of PLS-DA predictions based on the training samples used to train
the model (it will be higher than <strong>Q<sup>2</sup></strong> but it should not be used to choose the number of
components. This metric always increases with more components (estimation errorss might lead to temporary decreases)
which means it will overfit the model eventually.
<br>
<br>
After this optimization, a PLS model can be fitted with the chosen parameters and number of components. Model performance
can be estimated by accuracy, recall, precision and F1-score (the latter 3 weighted by class) using stratified fold
cross-validation. This cross-validation will also be used to estimate feature importance - variable importance in projection
(<strong>VIP</strong> scores). These are calculated based on Keiron Teilo O'Shea provided code in <a
href="https://www.researchgate.net/post/How-can-I-compute-Variable-Importance-in-Projection-VIP-in-Partial-Least-Squares-PLS"
target="_blank"
rel="nofollow">https://www.researchgate.net/post/How-can-I-compute-Variable-Importance-in-Projection-VIP-in-Partial-Least-Squares-PLS</a>.
This calculation can be slow when you have a high number of features. Importances estimated are then averaged across
the different folds. This can be iterated multiple times using randomized cross-validation folds. Model performance can
also be estimated with a Receiver Operating Characteristic (ROC) curve when only 2 classes are present.
<br>
<br>
Furthermore, a projection of the samples based on the PLS regression model using all available experimental samples on the
chosen Latent Variables akin to the PCA projections in the unsupervised analysis page is provided. Finally, Permutation
Testing (<strong>slow</strong>) can be performed to observe if the model and results obtained are significative.
"""


# Random Forest Description HTML in string format

rf_opening_string = """Here, <strong>Random Forest (RF)</strong> models can be built.
<br>
<br>
First, a focus on the optimization of the <strong>number of trees</strong> to use to build the Random Forest models is
available. This will allow the user to choose an optimal number of trees by observing the estimated accuracy of Random
Forest models (by stratified cross validation - number of folds <strong>K</strong> chosen by the user). The usual pattern
is that the accuracy will increase until a certain number of trees and will then fluctuate around that accuracy. Since RF
are somewhat resistant to overfitting, the value chosen will be one where the accuracy has stop increasing but not too high
as to make the model training too slow. A usual number used in our lab is 200.
<br>
<br>
After this optimization, a RF model can be fitted with the chosen parameters and number of trees. Model performance
can be estimated by accuracy, recall, precision and F1-score (the latter 3 weighted by class) using stratified fold
cross-validation. This cross-validation will also be used to estimate feature importance - <strong>Gini Importance</strong>.
Importances estimated are then averaged across the different folds. This can be iterated multiple times using randomized
cross-validation folds. Model performance can also be estimated with a Receiver Operating Characteristic (ROC) curve when
only 2 classes are present.
<br>
<br>
Finally, Permutation Testing (<strong>slow</strong>) can be performed to observe if the model and results obtained are
significative.
"""


# Permutation Test Description HTML in string format

permutation_test_description = '''Permutation tests permutate  the class labels of the samples, that is, all classes will
be randomized while maintaining the same number of samples per class and classes. For each permutation, model performance is
assessed by stratified cross-validation exactly as the previous sections. These performances are then compared with the
performance of a single iteration of a model built based on the non-permutated model that appears with a red line. Thus,
this red line might not be exactly the same value as the average model performance obtained in the supervised model (PLS-DA
or Random Forest) fitting section.
<br>
<br>
Thus, this is a test to observe model performance significancy, that is, if it is better than a random model. If it is,
then the remaining results from the important features give meaningful information.
<br>
<br>
<strong>Note: Permutation tests are slow to be computed.</strong>
<br>
<br>
P-value is calculated using the following equation:'''


# ROC Curve Description HTML in string format

ROC_curve_description = '''
<strong>ROC Curves</strong> are types of representation of the performance of supervised model that plot the True Positive
Rate by the False Positive Rate. Hence, one class has to be considered as the <strong><em>positive</em></strong> class.
Thus, this methodology, although possible in multiclass cases, is more suited for when you have a dataset with 2 classes.
When you have more than 2 classes, a ROC curve will be computed for each class considered as the positive by fitting a
"1vsAll" model, that is the class of each sample is either the current positive class or "Other". Thus, there will likely
be many more negative samples than positive samples in each case, greatly increasing the importance of the latter for the
curve of each class.
<br>
<br>
The model performance is determined by the <strong>Area Under the Curve</strong> or (<strong>AUC</strong>). When it is 1,
the model is perfect for classifying your data; when it is 0.5, the model is no better than a random coin toss.
<br>
<br>
Number of Iterations indicates how many times ROC curve results are computed with random k-fold stratified cross-validation.
This can help to have a more detailed ROC Curve especially when your dataset has a low number of samples.'''


# Univariate Analysis Page Opening HTML Description in string format

univ_opening_string = '''In this section, both Univariate Analysis and Fold-Change analysis are performed.
<br>
<br>
The Fold change is calculated in a dataset with missing values imputed and normalized after. <strong>This means that with
our very high number of missing values in FT-ICR-MS data, it affects the calculation of the fold change a lot. Thus, take
this fold changes values with a grain (or multiple grains that are actually more like rocks than grains) of salt.</strong>
<br>
<br>
Choose between the parametric <strong>t-test</strong> and non-parametric <strong>Mann-Whitney test</strong>.
<br>
<br>
<strong>Warning</strong>: This type of analysis is only done between 2 classes. If you have more than 2 classes, you can
also choose one as the control class and one as the test class to perform univariate analysis in the 1st tab.
<br>
<br>
Finally, when you have more than 2 classes, each unsupervised analysis will select the samples respective to the 2 classes,
filter and pre-treatment them the same way it was done on the full dataset before performing unsupervised analysis.
'''


# Van Krevelen Description HTML in string format

vk_opening_string = '''<strong>Van Krevelen Plot section</strong>
<br>
<br>
This section plots a Van Krevelen Plot for each of the classes under analysis. This is made by only considering metabolites
(features) that appear at least in one sample of said class.
<br>
Only metabolites with assigned formulas are considered. You can choose which formula annotation you want to use whether it
is a previous annotation performed, an annotation performed in this software, or even multiple different annotations
(<strong>Note: you HAVE to select at least one annotation</strong>). If multiple formulas can be assigned to a metabolite
whether within the same database annotation or different, they are both considered and plotted in the Van Krevelen.
<br>
<br>
You can also decide to colour the dots and make them different sized based on their average intensity in the corresponding
class using either a rank-based (more linear) approach or the logarithm of the averages intensity (less linear). You can
also choose a "midpoint", where the dots with avg. intensity below the midpoint % of the intensity of all features have a
more bluish colour, while those above have a redder colour.
'''


# Kendrick Mass Defect Plot Description HTML in string format

kmd_opening_string = '''<strong>Kendrick Mass Defect Plot section</strong>
<br>
<br>
This section plots a Kendrick Mass Defect Plot for each of the classes under analysis. This is plotted based on Neutral
Mass column selected.
<br>
Kendrick Nominal Mass and Mass Defect can be calculated in two ways:
<br>
- <strong>'Up'</strong>: by rounding the neutral mass up, thus the Mass Defects will vary between 0 and 1.
<br>
- <strong>'Nearest'</strong>: by rounding the neutral mass to the nearest integer, thus the Mass Defects will vary between -0.5 and 0.5.
<br>
<br>
You can decide to colour the dots based on the chemical composition series they belong to ('CHO', 'CHON', 'CHOP', 'CHONSP',
etc.) by selecting the formula columns of previous annotations, of the annotations performed in the software or a
combination of them. When, for one peak, there are multiple candidate formulas and they do not belong to the same chemical
composition series, they get assigned as <strong>'Ambiguous'</strong>. If <strong>None</strong> is selected, then the
points are not coloured by chemical composition series.
'''


# Chemical Composition Series Plot Description HTML in string format

ccs_opening_string = '''<strong>Chemical Composition Series section</strong>
<br>
<br>
This section plots a Chemical Composition Series bar plot indicating how many formulas of different chemical series ('CHO',
'CHON', 'CHOP', 'CHONSP', etc.) were assigned to samples of each class.
<br>
<br>
You can decide if you want to use formula annotations made previously, made in this software or a combination. <strong>If
multiple formulas</strong> can be assigned to the same <em>m/z</em> peak whether within the same formula annotation made or
between different annotations, <strong>each one will be counted in this plot</strong>. That is, if a peak in a class has 3
possible candidate formulas, 2 belonging to the 'CHO' series and another to the 'CHOP' series; then 2 formulas will be added
to the 'CHO' series and 1 to the 'CHOP' series. Thus, we are considering that the 3 elementary formulas are represented by
that peak (probably an overestimation). In all cases, it is rare to find multiple candidate formulas for the same m/z peak,
especially with extreme-resolution data. To provide an idea of how extensive this effect is, a description is also provided
detailing how many formulas are being considered for each class and from how many different features (<em>m/z</em> peaks)
they came from.
'''


# HMDB Pathway Assignment Page Description HTML in string format

path_assign_opening_string = """This page allows you to assign or match known metabolic pathways to HMDB annotations only. This
is made based on a file created from the <strong>RAMP database</strong> (<a href="https://rampdb.nih.gov/" target="_blank"
rel="nofollow">https://rampdb.nih.gov/</a>) where 55872 HMDB compounds have at least 1 corresponding pathway. The pathways shown
are aggregated from multiple sources: HMDB, Reactome, WikiPathways and KEGG; from where RAMP provides the information
(<a href="https://academic.oup.com/bioinformatics/article/39/1/btac726/6827287" target="_blank" rel="nofollow">https://academic.oup.com/bioinformatics/article/39/1/btac726/6827287</a>).
<br>
Thus, for this, there must be a column with the <strong>HMDB identifiers</strong> (e.g. 'HMDB0000001') from which the assignment
can be performed. The output gives the HMDB IDs and annotation names (if possible) as index in a DataFrame and the name and id of
the pathways that they belong to according to this built file. Your identifiers should have 7 numbers after "HMDB".
<br><br>
<strong>If no HMDB identifiers are present, you will not be able to perform this data analysis step</strong>."""
